import { StyleSheet } from 'react-native';

import type { AppPalette } from '../theme/palette';
import { Radius, Shadows, Spacing, Typography } from '../theme/tokens';

export function createStyles(palette: AppPalette) {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: palette.background,
    },
    screenShell: {
      flex: 1,
    },
    container: {
      paddingHorizontal: Spacing.lg,
      paddingTop: Spacing.sm,
      paddingBottom: 110,
      gap: Spacing.lg,
    },
    topSection: {
      gap: Spacing.md,
    },
    brandRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    brandMark: {
      width: 36,
      height: 36,
      borderRadius: Radius.pill,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: palette.brandSoft,
    },
    brandRing: {
      width: 22,
      height: 22,
      borderRadius: Radius.pill,
      borderWidth: 3,
      borderColor: palette.brand,
    },
    brandTextWrap: {
      flex: 1,
    },
    brandName: {
      color: palette.textPrimary,
      fontSize: 34,
      lineHeight: 38,
      fontWeight: Typography.weightExtraBold,
    },
    brandSubline: {
      color: palette.textSecondary,
      fontSize: 16,
      lineHeight: 22,
      fontWeight: Typography.weightMedium,
    },
    menuChip: {
      width: 42,
      height: 42,
      borderRadius: Radius.pill,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: palette.surfaceMuted,
      borderWidth: 1,
      borderColor: palette.border,
    },
    menuChipText: {
      color: palette.chipText,
      fontSize: Typography.caption,
      fontWeight: Typography.weightSemiBold,
    },
    greetingTitle: {
      color: palette.textPrimary,
      fontSize: 27,
      lineHeight: 32,
      fontWeight: Typography.weightBold,
    },
    greetingBody: {
      color: palette.textSecondary,
      fontSize: 15,
      lineHeight: 22,
      fontWeight: Typography.weightMedium,
    },
    rolesWrap: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: Spacing.xs,
    },
    roleChip: {
      backgroundColor: palette.surfaceMuted,
      borderRadius: Radius.pill,
      borderWidth: 1,
      borderColor: palette.border,
      paddingHorizontal: Spacing.sm,
      paddingVertical: Spacing.xs,
    },
    roleChipText: {
      color: palette.chipText,
      fontSize: Typography.caption,
      fontWeight: Typography.weightBold,
    },
    workspaceGridWrap: {
      gap: Spacing.sm,
    },
    workspaceRowTwo: {
      flexDirection: 'row',
      gap: Spacing.sm,
    },
    workspaceRowThree: {
      flexDirection: 'row',
      gap: Spacing.xs,
    },
    workspaceCardTwo: {
      flex: 1,
      backgroundColor: palette.surface,
      borderRadius: Radius.lg,
      borderWidth: 1,
      borderColor: palette.border,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.md,
      minHeight: 150,
      gap: Spacing.xs,
      ...Shadows.soft,
    },
    workspaceCardThree: {
      flex: 1,
      backgroundColor: palette.surface,
      borderRadius: Radius.md,
      borderWidth: 1,
      borderColor: palette.border,
      paddingHorizontal: Spacing.sm,
      paddingVertical: Spacing.sm,
      minHeight: 128,
      gap: Spacing.xs,
      ...Shadows.soft,
    },
    workspaceTitle: {
      color: palette.textPrimary,
      fontSize: 17,
      fontWeight: Typography.weightBold,
    },
    workspaceSummary: {
      color: palette.textSecondary,
      fontSize: Typography.label,
      lineHeight: 19,
    },
    stateBanner: {
      backgroundColor: palette.surface,
      borderRadius: Radius.md,
      borderWidth: 1,
      borderColor: palette.border,
      paddingVertical: Spacing.md,
      paddingHorizontal: Spacing.md,
      gap: Spacing.xs,
      ...Shadows.soft,
    },
    stateBadgeWrap: {
      flexDirection: 'row',
      gap: Spacing.sm,
    },
    stateBadge: {
      backgroundColor: palette.brandSoft,
      color: palette.success,
      paddingHorizontal: Spacing.sm,
      paddingVertical: Spacing.xs,
      borderRadius: Radius.pill,
      fontSize: Typography.caption,
      fontWeight: Typography.weightBold,
    },
    stateBadgeAlt: {
      backgroundColor: palette.surfaceMuted,
      color: palette.chipText,
      paddingHorizontal: Spacing.sm,
      paddingVertical: Spacing.xs,
      borderRadius: Radius.pill,
      fontSize: Typography.caption,
      fontWeight: Typography.weightBold,
    },
    stateBody: {
      color: palette.textMuted,
      fontSize: Typography.label,
      lineHeight: 18,
    },
    footerActions: {
      gap: Spacing.sm,
      paddingBottom: Spacing.sm,
    },
    bottomNav: {
      position: 'absolute',
      left: Spacing.lg,
      right: Spacing.lg,
      bottom: Spacing.md,
      backgroundColor: palette.surface,
      borderRadius: Radius.lg,
      borderWidth: 1,
      borderColor: palette.border,
      paddingVertical: Spacing.sm,
      paddingHorizontal: Spacing.sm,
      flexDirection: 'row',
      justifyContent: 'space-between',
      ...Shadows.soft,
    },
    bottomNavItem: {
      flex: 1,
      alignItems: 'center',
      gap: 2,
    },
    bottomNavIcon: {
      color: palette.textMuted,
      fontSize: Typography.label,
      fontWeight: Typography.weightBold,
    },
    bottomNavText: {
      color: palette.textMuted,
      fontSize: Typography.caption,
      fontWeight: Typography.weightMedium,
    },
    bottomNavTextActive: {
      color: palette.brand,
      fontSize: Typography.caption,
      fontWeight: Typography.weightBold,
    },
    sidebarLayer: {
      ...StyleSheet.absoluteFillObject,
      flexDirection: 'row',
      zIndex: 30,
    },
    sidebarBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(4, 10, 16, 0.45)',
    },
    sidebarPanel: {
      width: '74%',
      maxWidth: 320,
      backgroundColor: palette.surface,
      borderLeftWidth: 1,
      borderLeftColor: palette.border,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.lg,
      gap: Spacing.sm,
    },
    sidebarTitle: {
      color: palette.textPrimary,
      fontSize: Typography.title,
      fontWeight: Typography.weightBold,
    },
    sidebarSubtitle: {
      color: palette.textSecondary,
      fontSize: Typography.label,
      fontWeight: Typography.weightSemiBold,
      marginBottom: Spacing.xs,
    },
    sidebarItem: {
      backgroundColor: palette.surfaceMuted,
      borderWidth: 1,
      borderColor: palette.border,
      borderRadius: Radius.md,
      paddingHorizontal: Spacing.sm,
      paddingVertical: Spacing.sm,
      gap: Spacing.xxs,
    },
    sidebarItemTitle: {
      color: palette.textPrimary,
      fontSize: Typography.body,
      fontWeight: Typography.weightBold,
    },
    sidebarItemBody: {
      color: palette.textSecondary,
      fontSize: Typography.label,
      fontWeight: Typography.weightMedium,
    },
  });
}
