# Generated by Django 6.0.5 on 2026-07-05 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorydocument_purchase_pricelist'),
        ('products', '0007_salespricelist_service_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorydocumentline',
            name='purchase_pricelist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_document_lines', to='products.purchasepricelist'),
        ),
    ]
