# Generated by Django 6.0.5 on 2026-05-27 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_number', models.CharField(max_length=40, unique=True)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('adults', models.PositiveIntegerField(default=1)),
                ('children', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ENQUIRY', 'Enquiry'), ('TENTATIVE', 'Tentative'), ('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked In'), ('CHECKED_OUT', 'Checked Out'), ('CANCELLED', 'Cancelled')], default='ENQUIRY', max_length=30)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('channel_reference', models.CharField(blank=True, max_length=120)),
                ('deposit_due_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='business_partners.businesspartner')),
            ],
            options={
                'ordering': ['check_in_date', 'reservation_number'],
            },
        ),
    ]
