# Generated by Django 6.0.5 on 2026-05-27 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=40, unique=True)),
                ('department', models.CharField(choices=[('HOUSEKEEPING', 'Housekeeping'), ('MAINTENANCE', 'Maintenance'), ('CONCIERGE', 'Concierge'), ('SECURITY', 'Security')], max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('DISPATCHED', 'Dispatched'), ('RESOLVED', 'Resolved'), ('ESCALATED', 'Escalated')], default='OPEN', max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('sla_minutes', models.PositiveIntegerField(default=15)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='business_partners.businesspartner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
