# Generated by Django 6.0.5 on 2026-05-27 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolioLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('ROOM_CHARGE', 'Room Charge'), ('POS_CHARGE', 'POS Charge'), ('PAYMENT', 'Payment'), ('ADJUSTMENT', 'Adjustment')], max_length=30)),
                ('description', models.CharField(max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_number', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('LOCKED', 'Locked'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('charge_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('business_partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folios', to='business_partners.businesspartner')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
    ]
