# Generated by Django 6.0.5 on 2026-05-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('partner_type', models.CharField(choices=[('GUEST', 'Guest'), ('CORPORATE', 'Corporate Client'), ('TRAVEL_AGENT', 'Travel Agent'), ('SUPPLIER', 'Supplier'), ('STAFF', 'Staff')], default='GUEST', max_length=30)),
                ('display_name', models.CharField(max_length=180)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('nationality', models.CharField(blank=True, max_length=80)),
                ('id_document_type', models.CharField(blank=True, max_length=40)),
                ('id_document_number', models.CharField(blank=True, max_length=180)),
                ('visa_expiry_date', models.DateField(blank=True, null=True)),
                ('can_charge_to_room', models.BooleanField(default=False)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
    ]
