# Generated by Django 6.0.5 on 2026-05-27 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('legal_name', models.CharField(blank=True, max_length=180)),
                ('taxpayer_pin', models.CharField(blank=True, max_length=40)),
                ('business_email', models.EmailField(blank=True, max_length=254)),
                ('business_phone', models.CharField(blank=True, max_length=40)),
                ('physical_address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('branch_type', models.CharField(blank=True, max_length=80)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('kra_pin', models.CharField(blank=True, max_length=40)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_headquarters', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='organisation.organization')),
            ],
            options={
                'ordering': ['organization__name', 'name'],
            },
        ),
    ]
