# Generated by Django 6.0.5 on 2026-05-27 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_seed_roles_service_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('account_type', models.CharField(choices=[('BANK', 'Bank Account'), ('MPESA_TILL', 'M-Pesa Till'), ('CASH_TILL', 'Cash Till'), ('CARD_CLEARING', 'Card Clearing'), ('AR_LEDGER', 'Accounts Receivable')], max_length=30)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('account_number', models.CharField(blank=True, max_length=80)),
                ('till_number', models.CharField(blank=True, max_length=80)),
                ('ledger_account', models.CharField(max_length=100)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['account_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('method_type', models.CharField(choices=[('CASH', 'Cash'), ('MPESA', 'M-Pesa'), ('CARD', 'Card'), ('CITY_LEDGER', 'City Ledger'), ('ROOM_CHARGE', 'Room Charge'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=30)),
                ('opens_cash_drawer', models.BooleanField(default=False)),
                ('requires_reference', models.BooleanField(default=False)),
                ('requires_customer', models.BooleanField(default=False)),
                ('requires_room_verification', models.BooleanField(default=False)),
                ('posts_to_accounts_receivable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['method_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_point_kind', models.CharField(blank=True, max_length=40)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routing_rules', to='payments.bankaccount')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routing_rules', to='payments.paymentmethod')),
                ('service_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_routing_rules', to='users.servicepoint')),
            ],
            options={
                'ordering': ['priority', 'payment_method__name'],
            },
        ),
    ]
