# Generated by Django 6.0.5 on 2026-05-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], default='PERCENTAGE', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('allowed_roles', models.JSONField(blank=True, default=list)),
                ('service_point_kinds', models.JSONField(blank=True, default=list)),
                ('customer_group', models.CharField(blank=True, max_length=80)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaxConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('rate', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('calculation_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], default='PERCENTAGE', max_length=20)),
                ('application_order', models.PositiveIntegerField(default=1)),
                ('is_compound', models.BooleanField(default=False)),
                ('ledger_account', models.CharField(blank=True, max_length=80)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['application_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TaxCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('etims_code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taxes', models.ManyToManyField(blank=True, related_name='categories', to='taxes.taxconfiguration')),
            ],
            options={
                'verbose_name_plural': 'tax categories',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TaxOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('branch_code', models.CharField(max_length=80)),
                ('kra_pin', models.CharField(max_length=40)),
                ('integration_mode', models.CharField(choices=[('CLOUD_ETIMS', 'Cloud eTIMS'), ('OSCU_DEVICE', 'OSCU Device'), ('MANUAL', 'Manual Filing')], default='CLOUD_ETIMS', max_length=20)),
                ('endpoint_url', models.URLField(blank=True)),
                ('routing_key', models.CharField(blank=True, max_length=120)),
                ('certificate_alias', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['branch_code', 'name'],
                'unique_together': {('branch_code', 'kra_pin')},
            },
        ),
    ]
