# Generated by Django 6.0.5 on 2026-05-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_seed_products_matrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pack_size',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
        ),
    ]
