# Generated by Django 6.0.5 on 2026-05-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_pack_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='package_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual Item'), ('DOZEN', 'Dozen'), ('CARTON', 'Carton'), ('BALE', 'Bale'), ('BOX', 'Box'), ('CRATE', 'Crate'), ('BOTTLE', 'Bottle'), ('PACK', 'Pack')], default='INDIVIDUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
    ]
