# Generated by Django 6.0.5 on 2026-05-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_package_type_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='package_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual Item'), ('DOZEN', 'Dozen'), ('CARTON', 'Carton'), ('BALE', 'Bale'), ('BAG', 'Bag'), ('SACK', 'Sack'), ('BOX', 'Box'), ('CRATE', 'Crate'), ('BOTTLE', 'Bottle'), ('CAN', 'Can'), ('JAR', 'Jar'), ('PACK', 'Pack')], default='INDIVIDUAL', max_length=20),
        ),
    ]
