# Generated by Codex on 2026-05-28

from django.db import migrations, models
import django.db.models.deletion


def attach_seeded_service_points(apps, schema_editor):
    SalesPricelist = apps.get_model("products", "SalesPricelist")
    ServicePoint = apps.get_model("users", "ServicePoint")

    for pricelist in SalesPricelist.objects.filter(service_point__isnull=True).exclude(service_point_kind=""):
        service_point = ServicePoint.objects.filter(kind=pricelist.service_point_kind, is_active=True).order_by("name").first()
        if service_point:
            pricelist.service_point = service_point
            pricelist.save(update_fields=["service_point"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_seed_roles_service_points"),
        ("products", "0005_alter_product_package_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="salespricelist",
            name="service_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_pricelists",
                to="users.servicepoint",
            ),
        ),
        migrations.RunPython(attach_seeded_service_points, migrations.RunPython.noop),
    ]
