# Generated by Codex on 2026-05-28

from django.db import migrations, models


def seed_service_points(apps, schema_editor):
    SalesPricelist = apps.get_model("products", "SalesPricelist")
    ServicePoint = apps.get_model("users", "ServicePoint")

    for pricelist in SalesPricelist.objects.all():
        if pricelist.service_point_id:
            pricelist.service_points.add(pricelist.service_point_id)
            continue

        if pricelist.service_point_kind:
            point_ids = ServicePoint.objects.filter(
                kind=pricelist.service_point_kind,
                is_active=True,
            ).values_list("id", flat=True)
            pricelist.service_points.add(*point_ids)


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_salespricelist_service_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="salespricelist",
            name="service_points",
            field=models.ManyToManyField(
                blank=True,
                related_name="sales_pricelist_groups",
                to="users.servicepoint",
            ),
        ),
        migrations.RunPython(seed_service_points, migrations.RunPython.noop),
    ]
