# Generated by Django 6.0.5 on 2026-06-14 10:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('users', '0003_seed_roles_service_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Received'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('SERVED', 'Served'), ('INVOICED', 'Invoiced'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='GuestVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.CharField(max_length=40, unique=True)),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('service_area', models.CharField(max_length=80)),
                ('table_name', models.CharField(max_length=80)),
                ('guest_name', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CHECKOUT_REQUESTED', 'Checkout requested'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=30)),
                ('waiter_requested_at', models.DateTimeField(blank=True, null=True)),
                ('checkout_requested_at', models.DateTimeField(blank=True, null=True)),
                ('feedback_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('feedback_comment', models.TextField(blank=True)),
                ('arrived_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guest_visits', to='users.servicepoint')),
            ],
            options={
                'ordering': ['-arrived_at'],
            },
        ),
        migrations.AddField(
            model_name='salesorder',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='sales.guestvisit'),
        ),
    ]
