# Generated by Django 6.0.5 on 2026-06-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_salesorder_status_guestvisit_salesorder_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestvisit',
            name='waiter_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
