# Generated by Django 6.0.5 on 2026-06-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_guestvisit_waiter_acknowledged_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestvisit',
            name='waiter_keycloak_sub',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
