# Generated by Django 6.0.5 on 2026-06-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_guestvisit_waiter_keycloak_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='issued_by',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
