# Generated by Django 6.0.5 on 2026-06-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salesinvoice_issued_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
